### PR TITLE
Fix building on MinGW-w64

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Building on MinGW-w64 fails because all other mapfile have the `.hpp` extension except the one for MinGW-w64

### CODE REVIEW

**Comment by hobu** [comment]
Did someone ever directly include this file and would they ever be impacted by this filename change?

**Comment by MehdiChinoune** [comment]
Many files include this file but for different OSes, depends on include directory

**Comment by abellgithub** [comment]
This change seems fine to me.

**Comment by abellgithub** [comment]
No ifdefs. If you need special handling you need to make a mingw-specific file.

**Comment by MehdiChinoune** [comment]
> No ifdefs. If you need special handling you need to make a mingw-specific file.

A new file for a difference of one line?
Is it a new policy of not using 'ifdef's?. afaik this is a standard way of c/c++ programming.

**Comment by MehdiChinoune** [comment]
> Please copy the file and change as you like.

done.

**Comment by MehdiChinoune** [comment]
Ping!

**Pull request merged**
